WIP

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -13,85 +13,85 @@ jobs:
 # Format
 #
 
-  fmt:
-    runs-on: ubuntu-latest
-    steps:
-
-    - uses: actions/checkout@v2
-
-    - uses: actions/setup-python@v2
-      with:
-        python-version: 3.8
-
-    - run: python -m pip install black
-
-    - run: python -m black --check python
+#  fmt:
+#    runs-on: ubuntu-latest
+#    steps:
+#
+#    - uses: actions/checkout@v2
+#
+#    - uses: actions/setup-python@v2
+#      with:
+#        python-version: 3.8
+#
+#    - run: python -m pip install black
+#
+#    - run: python -m black --check python
 
 #
 # GPL
 #
 
-  gpl:
-    runs-on: ubuntu-latest
-    steps:
-
-    - uses: actions/checkout@v2
-
-    - run: TASK=buster+mcode ./dist/ci-run.sh -c --gpl --no-synth
+#  gpl:
+#    runs-on: ubuntu-latest
+#    steps:
+#
+#    - uses: actions/checkout@v2
+#
+#    - run: TASK=buster+mcode ./dist/ci-run.sh -c --gpl --no-synth
 
 #
 # GNU/Linux
 #
 
-  lin:
-    strategy:
-      fail-fast: false
-      max-parallel: 4
-      matrix:
-        backend: [
-          { os: 18, b: mcode },
-          { os: 20, b: mcode },
-          { os: 18, b: llvm-5.0 },
-          { os: 20, b: llvm-10 },
-          { os: 18, b: gcc-8.3.0 },
-          { os: 20, b: gcc-9.3.0 }
-        ]
-    runs-on: ubuntu-${{ matrix.backend.os }}.04
-    steps:
-
-    - uses: actions/checkout@v2
-
-    - name: Build and test GHDL in containers
-      run: |
-        TASK=ubuntu${{ matrix.backend.os }}+${{ matrix.backend.b }}${{ matrix.backend.v }} ./dist/ci-run.sh -c
-        mv ghdl-*-ubuntu${{ matrix.backend.os }}-*.tgz ghdl-gha-ubuntu-${{ matrix.backend.os }}.04-$(echo ${{ matrix.backend.b }} | sed 's#-.*##g').tgz
-
-    - uses: actions/upload-artifact@v2
-      with:
-        path: ghdl-gha-ubuntu-*.tgz
+#  lin:
+#    strategy:
+#      fail-fast: false
+#      max-parallel: 4
+#      matrix:
+#        backend: [
+#          { os: 18, b: mcode },
+#          { os: 20, b: mcode },
+#          { os: 18, b: llvm-5.0 },
+#          { os: 20, b: llvm-10 },
+#          { os: 18, b: gcc-8.3.0 },
+#          { os: 20, b: gcc-9.3.0 }
+#        ]
+#    runs-on: ubuntu-${{ matrix.backend.os }}.04
+#    steps:
+#
+#    - uses: actions/checkout@v2
+#
+#    - name: Build and test GHDL in containers
+#      run: |
+#        TASK=ubuntu${{ matrix.backend.os }}+${{ matrix.backend.b }}${{ matrix.backend.v }} ./dist/ci-run.sh -c
+#        mv ghdl-*-ubuntu${{ matrix.backend.os }}-*.tgz ghdl-gha-ubuntu-${{ matrix.backend.os }}.04-$(echo ${{ matrix.backend.b }} | sed 's#-.*##g').tgz
+#
+#    - uses: actions/upload-artifact@v2
+#      with:
+#        path: ghdl-gha-ubuntu-*.tgz
 
 #
 # MacOS
 #
 
-  osx:
-    runs-on: macOS-latest
-    steps:
-
-    - uses: actions/checkout@v2
-
-    - run: |
-        brew update || true
-        brew install p7zip
-        ./dist/macosx/install-ada.sh
-
-    - name: Build and test GHDL
-      run: |
-        PATH=$PWD/gnat/bin:$PATH
-        ./dist/ci-run.sh -c
-      env:
-        TASK: macosx+mcode
-        GITHUB_OS: ${{ runner.os }}
+#  osx:
+#    runs-on: macOS-latest
+#    steps:
+#
+#    - uses: actions/checkout@v2
+#
+#    - run: |
+#        brew update || true
+#        brew install p7zip
+#        ./dist/macosx/install-ada.sh
+#
+#    - name: Build and test GHDL
+#      run: |
+#        PATH=$PWD/gnat/bin:$PATH
+#        ./dist/ci-run.sh -c
+#      env:
+#        TASK: macosx+mcode
+#        GITHUB_OS: ${{ runner.os }}
 
 #
 # Windows
@@ -104,10 +104,10 @@ jobs:
       max-parallel: 2
       matrix:
         task: [
-          {installs: "MINGW32", pkg: "mcode"},
+          {installs: "MINGW32", pkg: "llvm"},
           #{installs: "MINGW32", pkg: "llvm"},  ! Not yet functional
           #{installs: "MINGW64", pkg: "mcode"}, ! mcode is not yet supported on win64
-          {installs: "MINGW64", pkg: "llvm"},
+          #{installs: "MINGW64", pkg: "llvm"},
         ]
     env:
       MINGW_INSTALLS: ${{ matrix.task.installs }}
@@ -156,26 +156,26 @@ jobs:
 # NIGHTLY
 #
 
-  nightly:
-    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
-    needs: [ lin, win ]
-    runs-on: ubuntu-latest
-    steps:
-
-    - uses: actions/download-artifact@v2
-
-    - uses: eine/tip@master
-      with:
-        token: ${{ secrets.GITHUB_TOKEN }}
-        tag: 'nightly'
-        files: artifact/*
-
-    - run: |
-        curl -X POST https://api.github.com/repos/ghdl/docker/dispatches \
-        -H "Content-Type: application/json" \
-        -H 'Accept: application/vnd.github.everest-preview+json' \
-        -H "Authorization: token ${{ secrets.GHDL_BOT }}" \
-        --data '{"event_type": "ghdl"}'
+#  nightly:
+#    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
+#    needs: [ lin, win ]
+#    runs-on: ubuntu-latest
+#    steps:
+#
+#    - uses: actions/download-artifact@v2
+#
+#    - uses: eine/tip@master
+#      with:
+#        token: ${{ secrets.GITHUB_TOKEN }}
+#        tag: 'nightly'
+#        files: artifact/*
+#
+#    - run: |
+#        curl -X POST https://api.github.com/repos/ghdl/docker/dispatches \
+#        -H "Content-Type: application/json" \
+#        -H 'Accept: application/vnd.github.everest-preview+json' \
+#        -H "Authorization: token ${{ secrets.GHDL_BOT }}" \
+#        --data '{"event_type": "ghdl"}'
 
 #---
 
